export const SCAMPER = [
    "Substitute",
    "Combine",
    "Adapt",
    "Modify",
    "Put-to-another-use",
    "Eliminate",
    "Reverse"
]
  
interface IQuestions {
    [key: string]: any;
}
export const questions: IQuestions = {
  "Substitute": [
    "What other types of ingredients or materials can be substituted?",
    "What other people, places, or things can be substituted?",
    "What other methods, processes, or procedures can be substituted?",
    "What other parts, components, or technology can be substituted?",
    "What other power/energy source can be substituted?",
    "What else can be replaced/interchanged?",
    "What are the most obvious things that can be substituted?",
    "What colors, textures, details, or finishes can be substituted?",
    "What part of the process can be substituted without affecting the whole project?",
    "Who or what can be substituted without affecting the process?",
    "What part in the process can be replaced with better alternatives?",
    "Can the project time or place be replaced?",
    "What will happen when we replace part of the project with another?",
    "Where else could you sell the product?",
    "Could we use another alternative of X?",
    "Can we substitute the current device with another better one?",
    "Can we replace the process with simpler one?",
    "What can I substitute so as to make an improvement?",
    "How can I substitute the place, time, materials or people?",
    "Can I substitute one part for another or change any parts?",
    "Can I replace someone involved?",
    "Can I change the rules?",
    "Should I change the name?",
    "Can I use other ingredients or materials?",
    "Can I use other processes or procedures?",
    "Can I change its shape, colour, roughness, sound or smell?",
    "Can I use this idea for other projects?",
    "Can I change my feelings or attitude towards it?",
  ],
  "Combine": [
    "What ingredients, materials, or parts can be combined?",
    "What two or more ideas can be combined?",
    "What else could be added, merged, or blended?",
    "What steps, functions, or processes can be combined?",
    "What features can be combined?",
    "What functions can be integrated/combined?",
    "How can we combine uses with something else?",
    "How can we combine our efforts and resources with others to succeed?",
    "Can we merge two steps of the process?",
    "Can we apply two processes at the same time?",
    "Can our company combine resources with another partner in the market?",
    "Can we mix two or more components together?",
    "Can we combine X and Y technologies?",
    "What ideas, materials, features, processes, people, products, or components can I combine?",
    "Can I combine or merge this or that with other objects?",
    "What can I combine so as to maximize the number of uses?",
    "What can I combine in order to lower the costs of production?",
    "Which materials could I combine?",
    "Where can I build synergy?",
    "Which are the best elements I can bring together so as to achieve a particular result?",
  ],
  "Adapt": [
    "What else is like/similar to this?",
    "What can be copied or imitated?",
    "How can the concept be adjusted/changed to fit another purpose?",
    "What has worked before?",
    "Who is/what is a highly successful role model to emulate?",
    "What product, service, or process is worthy of copying/emulating?",
    "What are five other uses or purposes we can imagine for this?",
    "How can the concept  be adapted to provide greater/additional value?",
    "What would we need to change to reach better results?",
    "What else could be done in this specific task?",
    "How can we improve the existing process?",
    "How can we adjust the existing product?",
    "How can we make the process more flexible?",
    "Which part of the product could I change?",
    "Could I change the characteristics of a component?",
    "Can I seek inspiration in other products or processes, but in a different context?",
    "Does the history offer any solutions?",
    "Which ideas could I adapt, copy, or borrow from other people’s products?",
    "What processes should I adapt?",
    "Can I adapt the context or target group?",
    "What can I adapt in this or that way in order to make this result?to achieve a particular result?",
  ],
  "Modify": [
    "In what ways can it be bigger, stronger, longer lasting, or more durable?",
    "In what ways can it be smaller, lighter, shorter, or more compact?",
    "In what ways can it be embellished, exaggerated, or more attention grabbing?",
    "How can it be faster or take less time?",
    "How can it be friendlier and easier to use?",
    "In what ways can color, form, function, or design be improved?",
    "What new/additional features can be added?",
    "What can add extra value?",
    "How will modifying the process improve results?",
    "What if we had a double consumer base?",
    "If the market was different, what would the process look like?",
    "Can we change the process to work more efficiently?",
    "What if the product is double the current size?",
    "What can I magnify or make larger?",
    "What can I tone down or delete?",
    "Could I exaggerate or overstate buttons, colours, size…?",
    "Could I grow the target group?",
    "What can be made higher, bigger, or stronger?",
    "Can I increase its speed or frequency?",
    "Can I add extra features?",
    "How can I add extra value?",
    "What can you remove or make smaller, condensed, lower, shorter or lighter—or streamline, split up or understate?",
    "What can I change in this way or that way so as to achieve such and such a result?",
  ],
  "Put-to-another-use": [
    "In what ways can the concept be used other than its original intended use?",
    "Who else might be able/interested to use the concept ?",
    "What other markets/niches can the concept be used in?",
    "What else can the concept be used for other than its original purpose?",
    "What are five different ways the concept can be used?",
    "What other unmet needs can the concept fulfill?",
    "What new ways can the concept be used, marketed, or sold?",
    "In what ways would a bunch of five-year-olds use/play with the concept?",
    "What other parts in the company can use the product?",
    "What are the benefits for the product if used elsewhere?",
    "What if we target another market segmentation for the current product?",
    "Can we add a specific step into the process to replace another?",
    "What are other ways can we use it?",
    "Can we recycle the waste for another use?",
    "What else can it be used for?",
    "How would a child use it?—an older person?",
    "How would people with different disabilities use it?",
    "Which other target group could benefit from this product?",
    "What other kind of user would need or want my product?",
    "Who or what else may be able to use it?",
    "Can it be used by people other than those it was originally intended for?",
    "Are there new ways to use it in its current shape or form?",
    "Would there be other possible uses if I were to modify the product?",
    "How can I reuse something in a certain way by doing what to it?",
  ],
  "Eliminate": [
    "What can be taken away, removed, or streamlined?",
    "What parts or pieces aren’t really necessary?",
    "What rules, steps, or procedures aren’t really necessary?",
    "What can be subtracted, deleted, or omitted?",
    "What would not be missed if eliminated?",
    "What is unnecessary or redundant?",
    "What aspect of our product or service provides little value?",
    "What can be minimized, condensed, or compacted?",
    "What would happened if we removed this part?",
    "How can we achieve the same output without specific part of the project?",
    "Do we need this specific part?",
    "What would we do if we had to work with half the resources?",
    "What can I remove without altering its function?",
    "Can I reduce time or components?",
    "What would happen if I removed a component or part of it?",
    "Can I reduce effort?",
    "Can I cut costs?",
    "How can I simplify it?",
    "What’s non-essential or unnecessary?",
    "Can I eliminate the rules?",
    "Can I make it smaller?",
    "Can I split my product into different parts?",
    "I can eliminate what by doing what?",
  ],
  "Reverse": [
    "Reverse",
    "What parts or features can be rearranged?",
    "What components can be interchanged?",
    "How can the concept be laid out in a different pattern/configuration?",
    "What can be reversed?",
    "What can be reorganized or transposed?",
    "What can be redesigned or re-engineered?",
    "What can be reformulated?",
    "What would be unexpected/provocative?",
    "What would happened if we reverse the process?",
    "How can we rearrange the current status for better output?",
    "What if we consider it backwards?",
    "Can we interchange elements?",
    "What can I rearrange in some way – can I interchange components, the pattern, or the layout?",
    "Can I change the pace or schedule?",
    "What would I do if part of your problem, product or process worked in reverse?",
    "I can rearrange what in what way such that this happens?",
  ],
};